import React from 'react';
import { Alert, Box, Button, Checkbox, Chip, Dialog, DialogActions, DialogContent, DialogTitle, FormControlLabel, Grid, IconButton, MenuItem, Paper, Snackbar, Stack, TextField, Typography } from '@mui/material';
import { ExternalLink, Pencil, Plus, QrCode, ReceiptText, Tag, Trash2 } from 'lucide-react';
import { useDispatch, useSelector } from 'react-redux'; import { useNavigate } from 'react-router-dom'; import { isAxiosError } from 'axios';
import type { AppDispatch, RootState } from '../../store'; import { fetchProducts } from '../../features/inventory/inventorySlice'; import api from '../../api/axios'; import type { OrderDraft } from '../../types/orderDraft';
import MenuDesignPicker from './MenuDesignPicker';
import MenuStatus from './MenuStatus';
import { DEFAULT_MENU_DESIGN, MENU_TEMPLATES, getMenuDesign, type MenuDesign } from './menuTemplates';

type DigitalMenu = { _id: string; name: string; tableName?: string; token: string; productIds: string[]; menuType?: 'menu' | 'deal'; sourceMenuId?: string | null; dealPrice?: number; design?: MenuDesign; status?: 'draft' | 'published'; hasUnpublishedChanges?: boolean }; type CreateMode = 'reuse' | 'deal';
const errorMessage = (e: unknown, fallback: string) => isAxiosError<{ message?: string }>(e) ? e.response?.data?.message || fallback : fallback;

const DigitalMenusPage: React.FC = () => {
 const dispatch = useDispatch<AppDispatch>(); const navigate = useNavigate(); const { products, loading: productsLoading, error: productsError } = useSelector((s: RootState) => s.inventory); const user = useSelector((s: RootState) => s.auth.user);
 const [menus,setMenus]=React.useState<DigitalMenu[]>([]); const [drafts,setDrafts]=React.useState<OrderDraft[]>([]); const [open,setOpen]=React.useState(false); const [mode,setMode]=React.useState<CreateMode>('reuse'); const [name,setName]=React.useState(''); const [dealPrice,setDealPrice]=React.useState(''); const [tableName,setTableName]=React.useState(''); const [productIds,setProductIds]=React.useState<string[]>([]); const [sourceMenuId,setSourceMenuId]=React.useState(''); const [editMenu,setEditMenu]=React.useState<DigitalMenu|null>(null); const [deleteMenu,setDeleteMenu]=React.useState<DigitalMenu|null>(null); const [qrMenu,setQrMenu]=React.useState<DigitalMenu|null>(null); const [slipDraft,setSlipDraft]=React.useState<OrderDraft|null>(null); const [deleteDraft,setDeleteDraft]=React.useState<OrderDraft|null>(null); const [error,setError]=React.useState(''); const [toast,setToast]=React.useState(''); const [saving,setSaving]=React.useState(false);
 const [publishingId,setPublishingId]=React.useState('');
 const publish=async(menu:DigitalMenu)=>{setPublishingId(menu._id);setError('');try{await api.post(`/digital-menus/${menu._id}/publish`);await load()}catch(e){setError(errorMessage(e,'Unable to publish this menu.'))}finally{setPublishingId('')}};
 const [design,setDesign]=React.useState<MenuDesign>({...DEFAULT_MENU_DESIGN}); const [productSearch,setProductSearch]=React.useState('');
 const canSendToPos=user?.role==='super_admin'||user?.digitalMenuAccess==='pos';
 const load=React.useCallback(async()=>{try{const [m,d]=await Promise.all([api.get<DigitalMenu[]>('/digital-menus'),api.get<OrderDraft[]>('/digital-menus/table-drafts')]);setMenus(m.data);setDrafts(d.data)}catch(e){setError(errorMessage(e,'Unable to load Digital Menus.'))}},[]);
 React.useEffect(()=>{void dispatch(fetchProducts(undefined));void load()},[dispatch,load]);
 const masters=menus.filter(m=>(m.menuType||'menu')==='menu'&&!m.sourceMenuId); const deals=(id:string)=>menus.filter(m=>m.menuType==='deal'&&m.sourceMenuId===id); const qrs=(id:string)=>menus.filter(m=>(m.menuType||'menu')==='menu'&&m.sourceMenuId===id);
 const reset=()=>{setName('');setDealPrice('');setTableName('');setProductIds([]);setSourceMenuId('');setProductSearch('');setOpen(false)}; const openCreate=(next:CreateMode,m?:DigitalMenu)=>{setMode(next);setDesign({...DEFAULT_MENU_DESIGN});setProductSearch('');setError('');setName('');setDealPrice('');setTableName('');setProductIds([]);setSourceMenuId(m?._id||masters[0]?._id||'');setOpen(true)}; const toggle=(id:string)=>setProductIds(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);
 const create=async()=>{setSaving(true);setError('');try{const data=mode==='reuse'?{tableName,sourceMenuId}:{name,productIds,menuType:'deal',sourceMenuId,dealPrice:Number(dealPrice)};await api.post('/digital-menus',data);reset();await load()}catch(e){const msg=errorMessage(e,'Unable to save this menu.');if(isAxiosError(e)&&e.response?.status===409)setToast(msg);else setError(msg)}finally{setSaving(false)}};
 const update=async()=>{if(!editMenu)return;setSaving(true);setError('');try{await api.put(`/digital-menus/${editMenu._id}`,{name,productIds,...(editMenu.menuType==='deal'?{dealPrice:Number(dealPrice)}:{design})});setEditMenu(null);await load()}catch(e){setError(errorMessage(e,'Unable to update this menu.'))}finally{setSaving(false)}}; const remove=async()=>{if(!deleteMenu)return;try{await api.delete(`/digital-menus/${deleteMenu._id}`);setDeleteMenu(null);await load()}catch(e){setError(errorMessage(e,'Unable to remove this item.'))}}; const removeDraft=async()=>{if(!deleteDraft)return;try{await api.delete(`/order-drafts/${deleteDraft._id}`);setDeleteDraft(null);await load()}catch(e){setError(errorMessage(e,'Unable to remove this table order.'))}}; const url=(token:string)=>`${window.location.origin}/menu/${token}`;
 const validPrice=dealPrice.trim()!==''&&Number.isFinite(Number(dealPrice))&&Number(dealPrice)>=0; const startEdit=(m:DigitalMenu)=>{if(m.menuType!=='deal'&&!m.sourceMenuId){navigate(`/digital-menus/${m._id}/edit`);return;}setEditMenu(m);setDesign(getMenuDesign(m.design));setProductSearch('');setError('');setName(m.name);setProductIds(m.productIds);setDealPrice(m.dealPrice===undefined?'':String(m.dealPrice))}; const valid=mode==='reuse'?!!(sourceMenuId&&tableName.trim()):!!(sourceMenuId&&name.trim()&&productIds.length&&validPrice); const filteredProducts=products.filter(p=>`${p.name} ${p.category}`.toLowerCase().includes(productSearch.toLowerCase())); const picker=<Stack spacing={1}><TextField size="small" label="Search products" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/><Typography variant="caption" color="text.secondary">{productIds.length} products selected</Typography>{productsLoading?<Typography color="text.secondary">Loading products...</Typography>:productsError?<Alert severity="error" action={<Button onClick={()=>void dispatch(fetchProducts({force:true}))}>Retry</Button>}>{productsError}</Alert>:!products.length?<Alert severity="info">Add products in Inventory first, then select them for your menu.</Alert>:<Box sx={{maxHeight:280,overflowY:'auto',border:'1px solid',borderColor:'divider',borderRadius:2,px:1}}>{filteredProducts.map(p=><FormControlLabel key={p.id} control={<Checkbox checked={productIds.includes(p.id)} onChange={()=>toggle(p.id)}/>} label={`${p.name} - Rs. ${p.salePrice??p.price}`} sx={{display:'flex',m:0}}/>)}{!filteredProducts.length&&<Typography color="text.secondary" sx={{p:2}}>No products match your search.</Typography>}</Box>}</Stack>;

 return <Box><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2} sx={{mb:3}}><Box><Stack direction="row" spacing={1} alignItems="center"><QrCode size={30}/><Typography variant="h4" fontWeight={900}>Digital Menus</Typography></Stack><Typography color="text.secondary" sx={{mt:.75}}>Save drafts and publish one menu at a time. Table QR codes always use your active menu.</Typography></Box><Stack direction="row" spacing={1} alignItems="center" sx={{flexShrink:0,flexWrap:'wrap',gap:1}}>{masters.length>0&&<Button variant="outlined" startIcon={<QrCode size={18}/>} onClick={()=>openCreate('reuse',masters[0])}>Create Table QR</Button>}<Button variant="contained" startIcon={<Plus size={18}/>} onClick={()=>navigate('/digital-menus/create')}>Create Menu</Button></Stack></Stack>
 {error&&<Alert severity="error" sx={{mb:2}} onClose={()=>setError('')}>{error}</Alert>}<Snackbar open={!!toast} autoHideDuration={5000} onClose={()=>setToast('')}><Alert severity="warning" variant="filled">{toast}</Alert></Snackbar>
 <Grid container spacing={2.5}>{masters.map(m=>{const ds=deals(m._id), qs=qrs(m._id);return <Grid key={m._id} size={{xs:12,md:6,xl:4}}><Paper variant="outlined" sx={{p:2.25,borderRadius:3}}><Stack direction="row" justifyContent="space-between" alignItems="start"><Box><Stack direction="row" spacing={1} alignItems="center"><Typography fontWeight={900}>{m.name}</Typography><MenuStatus published={m.status==='published'}/></Stack>{m.hasUnpublishedChanges&&<Typography variant="caption" color="text.secondary">Unpublished draft changes</Typography>}<Typography variant="body2" color="text.secondary" sx={{mt:.5}}>{m.design?.templateId==='custom'?'Custom menu':MENU_TEMPLATES.find(t=>t.design.templateId===(m.design?.templateId||'classic'))?.name} - {m.productIds.length} menu items · {ds.length} deals · {qs.length} QR codes</Typography></Box><Stack direction="row"><IconButton size="small" onClick={()=>startEdit(m)}><Pencil size={17}/></IconButton><IconButton color="error" size="small" onClick={()=>setDeleteMenu(m)}><Trash2 size={17}/></IconButton></Stack></Stack>{ds.length>0&&<Stack direction="row" spacing={.75} useFlexGap flexWrap="wrap" sx={{mt:1.5}}>{ds.map(d=><Chip key={d._id} size="small" color="secondary" label={`${d.name}${d.dealPrice!==undefined?` - Rs. ${d.dealPrice}`:' - Set price'}`} onClick={()=>startEdit(d)} onDelete={()=>setDeleteMenu(d)}/>)}</Stack>}<Stack direction="row" spacing={1} useFlexGap flexWrap="wrap" sx={{mt:2}}><Button size="small" variant="outlined" startIcon={<Tag size={15}/>} onClick={()=>openCreate('deal',m)}>Add Deal</Button><Button size="small" variant="outlined" startIcon={<QrCode size={15}/>} onClick={()=>openCreate('reuse',m)}>Create QR</Button><Button size="small" variant="contained" startIcon={<ExternalLink size={15}/>} onClick={()=>navigate(`/digital-menus/${m._id}/preview`)}>Preview Draft</Button>{m.status==='published'&&<Button size="small" startIcon={<ExternalLink size={15}/>} onClick={()=>window.open(url(m.token),'_blank','noopener,noreferrer')}>View live</Button>}{(m.status!=='published'||m.hasUnpublishedChanges)&&<Button size="small" color="success" variant="contained" disabled={!!publishingId} onClick={()=>void publish(m)}>{publishingId===m._id?'Publishing...':m.status==='published'?'Publish changes':'Publish'}</Button>}{qs.length>0&&<Button size="small" onClick={()=>setQrMenu(m)}>View QRs</Button>}</Stack></Paper></Grid>})}</Grid>
 {!masters.length&&<Paper variant="outlined" sx={{textAlign:'center',py:7,borderRadius:3}}><QrCode size={38}/><Typography fontWeight={800} sx={{mt:1}}>No menus yet</Typography><Typography variant="body2" color="text.secondary">Build your own design or pick a ready-made template, then add your products.</Typography><Button variant="contained" startIcon={<Plus size={18}/>} sx={{mt:2}} onClick={()=>navigate('/digital-menus/create')}>Create Menu</Button></Paper>}
 <Typography variant="h5" fontWeight={900} sx={{mt:5,mb:2}}>Table Draft Orders</Typography><Grid container spacing={2}>{drafts.map(d=><Grid key={d._id} size={{xs:12,md:6,xl:4}}><Paper variant="outlined" sx={{p:2.25,borderRadius:3}}><Stack direction="row" justifyContent="space-between"><Box><Chip label={d.digitalMenuTable||'Table'} color="secondary" size="small"/><Typography fontWeight={900} sx={{mt:1}}>{d.items.map(i=>`${i.quantity}× ${i.productName}`).join(', ')}</Typography></Box><Stack direction="row"><IconButton size="small" onClick={()=>setSlipDraft(d)} aria-label={`View ${d.digitalMenuTable||'table'} slip`} title="View slip"><ReceiptText size={21}/></IconButton><IconButton color="error" size="small" onClick={()=>setDeleteDraft(d)} aria-label={`Delete ${d.digitalMenuTable||'table'} order`} title="Delete table order"><Trash2 size={18}/></IconButton></Stack></Stack><Typography variant="caption" color="text.secondary" display="block" sx={{my:1.5}}>Updated {new Date(d.updatedAt).toLocaleString()}</Typography>{canSendToPos?<Button fullWidth variant="contained" onClick={()=>navigate(`/pos?draft=${d._id}`)}>Send to POS Billing</Button>:<Alert severity="info" icon={false} sx={{py:.3}}>Menu-only access: billing is disabled.</Alert>}</Paper></Grid>)}</Grid>{!drafts.length&&<Typography color="text.secondary">Customer QR orders will appear here table-wise.</Typography>}
 <Dialog open={open} onClose={()=>{if(!saving)reset()}} fullWidth maxWidth="sm"><DialogTitle>{mode==='reuse'?'Create QR Code':'Add Deal to Menu'}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>
 {error&&<Alert severity="error">{error}</Alert>}
 {masters.length>1&&<TextField select label="Menu" value={sourceMenuId} onChange={e=>setSourceMenuId(e.target.value)} required>{masters.map(m=><MenuItem key={m._id} value={m._id}>{m.name}</MenuItem>)}</TextField>}
 {mode==='reuse'?<><Typography color="text.secondary">This table QR always shows your published menu and its published deals. You can switch the active menu without replacing this QR.</Typography><TextField label="Unique table number / name" value={tableName} onChange={e=>setTableName(e.target.value)} placeholder="Table 002" required/></>:<>
 <TextField label="Deal name" value={name} onChange={e=>setName(e.target.value)} placeholder="Lunch Deal" slotProps={{htmlInput:{maxLength:100}}} required/>
 <TextField label="Deal price (Rs.)" type="number" value={dealPrice} onChange={e=>setDealPrice(e.target.value)} slotProps={{htmlInput:{min:0,step:"0.01"}}} helperText="One price for all included items together" required/><Typography fontWeight={800}>Choose items included in this deal</Typography>{picker}
 </>}
 </Stack></DialogContent><DialogActions><Button disabled={saving} onClick={reset}>Cancel</Button><Button variant="contained" disabled={saving||!valid||(mode==='deal'&&productsLoading)} onClick={()=>void create()}>{saving?'Saving...':mode==='reuse'?'Create QR':'Add Deal'}</Button></DialogActions></Dialog>
 <Dialog open={!!editMenu} onClose={()=>{if(!saving)setEditMenu(null)}} fullWidth maxWidth={editMenu?.menuType==='deal'?'sm':'md'}><DialogTitle>{editMenu?.menuType==='deal'?'Edit Deal':'Edit Menu'}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>{error&&<Alert severity="error">{error}</Alert>}{editMenu?.menuType!=='deal'&&<MenuDesignPicker design={design} onChange={setDesign} name={name} products={products.filter(p=>productIds.includes(p.id))}/>}<TextField label={editMenu?.menuType==='deal'?'Deal name':'Menu name'} value={name} onChange={e=>setName(e.target.value)} required/>{editMenu?.menuType==='deal'&&<TextField label="Deal price (Rs.)" type="number" value={dealPrice} onChange={e=>setDealPrice(e.target.value)} slotProps={{htmlInput:{min:0,step:"0.01"}}} helperText="One price for all included items together" required/>}<Typography fontWeight={800}>Menu items</Typography>{picker}</Stack></DialogContent><DialogActions><Button disabled={saving} onClick={()=>setEditMenu(null)}>Cancel</Button><Button variant="contained" disabled={saving||productsLoading||!name.trim()||!productIds.length||(editMenu?.menuType==='deal'&&!validPrice)} onClick={()=>void update()}>{saving?'Saving...':'Save changes'}</Button></DialogActions></Dialog>
 <Dialog open={!!qrMenu} onClose={()=>setQrMenu(null)} fullWidth maxWidth="sm"><DialogTitle>{qrMenu?.name} QR Codes</DialogTitle><DialogContent><Stack spacing={1.5} sx={{pt:.5}}>{qrMenu&&qrs(qrMenu._id).map(q=><Paper key={q._id} variant="outlined" sx={{p:1.5,borderRadius:2}}><Stack direction="row" justifyContent="space-between" alignItems="center" gap={1}><Box><Typography fontWeight={800}>{q.tableName}</Typography><Typography variant="caption" color="text.secondary">Uses {qrMenu.name}</Typography></Box><Stack direction="row" alignItems="center"><Button size="small" startIcon={<ExternalLink size={15}/>} onClick={()=>window.open(url(q.token),'_blank')}>Preview</Button><IconButton size="small" onClick={()=>navigator.clipboard.writeText(url(q.token))} aria-label={`Copy ${q.tableName} link`} title="Copy link"><QrCode size={17}/></IconButton><IconButton color="error" size="small" onClick={()=>{setQrMenu(null);setDeleteMenu(q)}} aria-label={`Delete ${q.tableName}`} title="Delete QR"><Trash2 size={17}/></IconButton></Stack></Stack></Paper>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setQrMenu(null)}>Close</Button></DialogActions></Dialog>
 <Dialog open={!!slipDraft} onClose={()=>setSlipDraft(null)} maxWidth="xs" fullWidth><DialogTitle>{slipDraft?.digitalMenuTable||'Table'} — Order Slip</DialogTitle><DialogContent><Stack spacing={1} sx={{pt:.5}}>{slipDraft?.items.map(item=><Stack key={item.productId} direction="row" justifyContent="space-between" gap={2}><Typography>{item.quantity}× {item.productName}</Typography><Typography fontWeight={700}>Rs. {item.quantity*item.unitPrice}</Typography></Stack>)}<Box sx={{borderTop:'1px solid',borderColor:'divider',pt:1,mt:.5}}><Stack direction="row" justifyContent="space-between"><Typography fontWeight={900}>Total</Typography><Typography fontWeight={900}>Rs. {(slipDraft?.items.reduce((total,item)=>total+item.quantity*item.unitPrice,0)??0)}</Typography></Stack></Box><Typography variant="caption" color="text.secondary">Updated {slipDraft&&new Date(slipDraft.updatedAt).toLocaleString()}</Typography></Stack></DialogContent><DialogActions><Button onClick={()=>setSlipDraft(null)}>Close</Button></DialogActions></Dialog>
 <Dialog open={!!deleteDraft} onClose={()=>setDeleteDraft(null)} maxWidth="xs" fullWidth><DialogTitle>Delete table order?</DialogTitle><DialogContent><Typography color="text.secondary">Delete the order draft for <strong>{deleteDraft?.digitalMenuTable||'this table'}</strong>? This cannot be undone.</Typography></DialogContent><DialogActions><Button onClick={()=>setDeleteDraft(null)}>Cancel</Button><Button color="error" variant="contained" onClick={()=>void removeDraft()}>Delete</Button></DialogActions></Dialog>
 <Dialog open={!!deleteMenu} onClose={()=>setDeleteMenu(null)} maxWidth="xs" fullWidth><DialogTitle>Delete item?</DialogTitle><DialogContent><Typography color="text.secondary">Are you sure you want to delete <strong>{deleteMenu?.name}</strong>{deleteMenu?.tableName?` for ${deleteMenu.tableName}`:''}? This cannot be undone.</Typography></DialogContent><DialogActions><Button onClick={()=>setDeleteMenu(null)}>Cancel</Button><Button color="error" variant="contained" onClick={()=>void remove()}>Delete</Button></DialogActions></Dialog></Box>;
}; export default DigitalMenusPage;
